### ISSUE TITLE
run_case时报错

### ISSUE THREAD

**Issue by Lance95Lance** [wuranxu/webTest#1]
windows 10, pycharm venv下的虚拟py3.4

已经执行过install.py

启动run_case时,有如下几个问题：

1.找不到.log文件  (新建文件夹和.log文件后解决)

Traceback (most recent call last):
  File "D:/UI/webTest/run_case.py", line 9, in <module>
    from TestResult.Suite import Suite
  File "D:\UI\webTest\TestResult\Suite.py", line 7, in <module>
    class Suite(unittest.TestSuite):
  File "D:\UI\webTest\TestResult\Suite.py", line 9, in Suite
    logger = Logger().logger
  File "D:\UI\webTest\Tools\logger.py", line 20, in __init__
    os.path.join(Config.LOG_DIR, filename)), encoding="utf-8")
  File "D:\Python34\lib\logging\__init__.py", line 999, in __init__
    StreamHandler.__init__(self, self._open())
  File "D:\Python34\lib\logging\__init__.py", line 1023, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\UI\\webTest\\Log\\webdriver_test.log'

2.xmind_reader文件中引入xmind找不到模块:
目测可能是写错大小写了，改成import Xmind后解决

3.加载xmind文件时报错：
解决上面两个问题后，报这个：

找到浏览器对应驱动版本号: 2.40
系统已存在chromedriver, 无需下载!
Traceback (most recent call last):
  File "D:/UI/webTest/run_case.py", line 64, in <module>
    run()
  File "D:/UI/webTest/run_case.py", line 55, in run
    suite = create_suite()
  File "D:/UI/webTest/run_case.py", line 19, in create_suite
    get_xmind_case()    # 生成Xmind
  File "D:/UI/webTest/run_case.py", line 38, in get_xmind_case
    xd = Xmind(file)
  File "D:\UI\webTest\Tools\xmind_reader.py", line 15, in __init__
    self.reader = Xmind.load(filepath)
AttributeError: type object 'Xmind' has no attribute 'load'

希望能帮忙解决下

**Comment by wuranxu** [comment]
需要用到xmind模块吗？这功能很鸡肋，考虑去除。xmind应该是小写的，这个模块不支持pip安装，install.py采用的是下载zip自动解压安装。可能是有问题···
感谢提出问题。。

**Comment by Lance95Lance** [comment]
@wuranxu 其实感觉xmind解析这个功能蛮不错的，如果提供给不会写case的黑盒用感觉蛮方便的哈哈哈哈。去除这模块也可以。

环境准备方面的，大佬可以专门写个环境准备的文章啊，因为我看代码里环境准备的代码量也不少，如果分离的话会好些，工程体积也小点，一些拙见，仅供参考

**Comment by wuranxu** [comment]
xmind暂时没有去，因为就是简单做了一个小功能。如果真要用起来，还是需要回炉重造的。而且前同事用的时候反馈说不好用，所以就决定去掉了。

Log目录不存在的问题已解决，目前截图/新增日志文件/检查浏览器驱动都会自动创建目录。
xmind如果要去也很快，我本地win10环境测试是可以的。

**Comment by wuranxu** [comment]
环境配置问题，确实麻烦了点。不过想的是能少花时间在配置环境上，所以一开始是没有做install.py的，是需要手动安装包的。后来无聊做了一下，不去掉也没关系。

感谢提出的宝贵意见，因为做完这个项目就离职了。QA应该也没用这个框架了，而我由于最近都没做webUI自动化就没有更新维护，有点可惜。

**Comment by TeeangeHWei** [comment]
![image](https://user-images.githubusercontent.com/17446000/58844831-790dfc00-86ab-11e9-8bd3-19ae5baf9f04.png)
pycharm运行后出现这里说的索引超出了范围，但是在命令行下则没有报这个错误。望解决呢

**Comment by TeeangeHWei** [comment]
> ![image](https://user-images.githubusercontent.com/17446000/58844831-790dfc00-86ab-11e9-8bd3-19ae5baf9f04.png)
> pycharm运行后出现这里说的索引超出了范围，但是在命令行下则没有报这个错误。望解决呢

额。是因为安装错了Xmind的工具包。安装好之后，但是新的问题又来了
![image](https://user-images.githubusercontent.com/17446000/58845176-ca6abb00-86ac-11e9-9bca-f10ad1a37f58.png)

**Comment by wuranxu** [comment]
@TeeangeHWei 这个不太清楚，xmind功能没怎么经过测试。当初只是一个方向，你的xmind文件长啥样可以看一下吗？

**Comment by TeeangeHWei** [comment]
@wuranxu 但是我用pycharm运行就是报xmind的错。xmind文件我是从Project Interpreter 导入包的 结构是这样的
![image](https://user-images.githubusercontent.com/17446000/58849126-bed2c080-86bb-11e9-9615-ac1af9b9cfe0.png)

**Comment by wuranxu** [comment]
@TeeangeHWei 
https://codeload.github.com/xmindltd/xmind-sdk-python/zip/master
下载解压后, 进入目录执行:
python3 setup.py install

不要用pycharm安装, 另外检查下本地是不是有2个python3版本
