### ISSUE TITLE
请问单个用例文件可以执行多个操作吗，还是只能一个用例写一个文件

### ISSUE THREAD

**Issue by WeiqinChina** [wuranxu/webTest#2]
![image](https://user-images.githubusercontent.com/47628295/100211061-a1945080-2f46-11eb-8df1-f2ae35be6dd8.png)

**Comment by wuranxu** [comment]
可以执行多个操作，test方法可以命名为test_01和test_02，当然最好命名的时候带上具体的业务内容，不要以这种数字结尾。

**Comment by WeiqinChina** [comment]
![image](https://user-images.githubusercontent.com/47628295/100212135-f1bfe280-2f47-11eb-882b-f8ecde244cca.png)
我试过改方法名，但是改了之后有新的错误

**Comment by WeiqinChina** [comment]
![image](https://user-images.githubusercontent.com/47628295/100212499-5f6c0e80-2f48-11eb-8920-308cc572b4b3.png)
这里是以test来过滤的，正常来讲我也是以test开头的，不知道为啥会报错

**Comment by wuranxu** [comment]
好的，我来修复一下这个问题，稍等下~

**Comment by WeiqinChina** [comment]
好的，非常感谢~

**Comment by wuranxu** [comment]
可以了，记得先保留本地的case代码，然后pull一下~

**Comment by WeiqinChina** [comment]
好了，非常感谢

**Comment by WeiqinChina** [comment]
试了一下还有点瑕疵，执行case的时候每次都会进行一次浏览器的打开关闭的操作，实际上我只需要打开一次，整个测试集跑完之后关掉浏览器就好了

**Comment by wuranxu** [comment]
> 试了一下还有点瑕疵，执行case的时候每次都会进行一次浏览器的打开关闭的操作，实际上我只需要打开一次，整个测试集跑完之后关掉浏览器就好了

这个可以用setUpClass, 可以百度查一下相关的用法，打开2次浏览器是因为setUp执行了2次。

**Comment by WeiqinChina** [comment]
好的，谢谢，我去学习一下

**Comment by wuranxu** [comment]
> 好的，谢谢，我去学习一下

有点问题，对于setUpclass支持不太够，涉及到报告那块，默认现在是以setUp去处理的，所以后面要兼容的话可能需要等空了才行了。

**Comment by wuranxu** [comment]
> 好的，谢谢，我去学习一下

目前已经可以支持setUpClass， 请拉最新代码。用例继承这个类即可: BaseCaseCls

**Comment by WeiqinChina** [comment]
> > 好的，谢谢，我去学习一下
> 
> 目前已经可以支持setUpClass， 请拉最新代码。用例继承这个类即可: BaseCaseCls

感谢

**Comment by WeiqinChina** [comment]
> > 好的，谢谢，我去学习一下
> 
> 目前已经可以支持setUpClass， 请拉最新代码。用例继承这个类即可: BaseCaseCls

今天调试发现报告里的错误截图都是同一张图片，不知道是不是我使用的问题

**Comment by wuranxu** [comment]
> > > 好的，谢谢，我去学习一下
> > 
> > 
> > 目前已经可以支持setUpClass， 请拉最新代码。用例继承这个类即可: BaseCaseCls
> 
> 今天调试发现报告里的错误截图都是同一张图片，不知道是不是我使用的问题

已经修复好了，是支持你这种一个class多个case的情况时忘记考虑截图了。

**Comment by WeiqinChina** [comment]
厉害了~

**Comment by WeiqinChina** [comment]
![image](https://user-images.githubusercontent.com/47628295/100993628-9cf81980-3590-11eb-8271-7e9c4cd0dc13.png)
不好意思一直麻烦你~测试用例很多的情况下，这个是一直累加下去的吗，这个测试用例能否根据用例名称或者套件名称折叠

**Comment by wuranxu** [comment]
> ![image](https://user-images.githubusercontent.com/47628295/100993628-9cf81980-3590-11eb-8271-7e9c4cd0dc13.png)
> 不好意思一直麻烦你~测试用例很多的情况下，这个是一直累加下去的吗，这个测试用例能否根据用例名称或者套件名称折叠

目前是没有支持的，暂时也没有支持的计划。
