### ISSUE TITLE
请教下，代码里哪里redirect到了bing的网址

### ISSUE THREAD

**Issue by lynnxia517** [wuranxu/webTest#4]
因为我并未看到有URL的地方。因为想要验证登陆其他url是否可行

**Comment by wuranxu** [comment]
> 因为我并未看到有URL的地方。因为想要验证登陆其他url是否可行

https://github.com/wuranxu/webTest/blob/master/page/login.py    具体的登录操作在这里
https://github.com/wuranxu/webTest/blob/master/config.py           url在配置文件里，URL变量

**Comment by lynnxia517** [comment]
谢谢。知道了。
