### ISSUE TITLE
请教下 在你的这个项目的基础上，要用clear()方法怎么用呢

### ISSUE THREAD

**Issue by lxia-hub** [wuranxu/webTest#6]
想用selenium的clear()和send_keys()方法，在你已经封装了Location的基础上怎么用呢。找不到这个方法。

**Comment by wuranxu** [comment]
可以用self.driver.send_keys()或者self.send()

**Comment by lxia-hub** [comment]
self.driver找不到这个方法。还有一个问题，skipe_suite怎么配置呢。能否举个例子。

**Comment by wuranxu** [comment]
> self.driver找不到这个方法。还有一个问题，skipe_suite怎么配置呢。能否举个例子。

继承BaseCaseCls这个类，就可以获取到self.driver和封装后的self.send等方法，详情可以参考tests/Search.py

跳过暂时可能没有支持，如果有需要可以补上。

**Comment by lxia-hub** [comment]
嗯嗯 跳过还是很有实际应用场景的，如果你有空的话。多谢：）

**Comment by lxia-hub** [comment]
我还有一个疑问，就是为什么要分别写base_case和base_case_class给两个测试子集Example和XmindTestCase下面的用例

**Comment by wuranxu** [comment]
> 我还有一个疑问，就是为什么要分别写base_case和base_case_class给两个测试子集Example和XmindTestCase下面的用例

之前有一个需求，是setUp方法只执行一次，做了个兼容。普通case的话执行的时候会每次都setUp/tearDown，但是base_case_class里面只会执行一次setUp/teardown

**Comment by lxia-hub** [comment]
多谢答疑，明白了
